version: 2
updates:
  - package-ecosystem: npm
    directory: /web/capacitor-ui
    schedule:
      interval: monthly
    groups:
      frontend-minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]
    open-pull-requests-limit: 5

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: monthly
    groups:
      android-minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
